line-length = 120
indent-width = 4
target-version = "py314"

[format]
exclude = ["*.pyi"]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
