# Generated by Django 6.0.2 on 2026-02-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryPage',
            new_name='BlogCategoryPage',
        ),
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='BlogPostPage',
        ),
    ]
