# Generated by Django 6.0.2 on 2026-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_categorypage_blogcategorypage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
