# Generated by Django 6.0.2 on 2026-02-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
