# Generated by Django 6.0.2 on 2026-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutpage_contactpage_innerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_button',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True),
        ),
    ]
