[supervisord]
nodaemon=true

[program:collectstatic]
command=/usr/local/bin/python manage.py collectstatic --noinput
directory=/app/backend
priority=5
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/var/log/collectstatic.log
stderr_logfile=/var/log/collectstatic.err


[program:gunicorn]
command=/usr/local/bin/gunicorn core.wsgi:application --bind 127.0.0.1:8000 --workers 3
directory=/app/backend
priority=10
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/var/log/gunicorn.log
stderr_logfile=/var/log/gunicorn.err

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=20
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx.err
